version: 3
workdir: internal

allow:
  depOnAnyVendor: false

excludeFiles:
  - "^.*_test\\.go$"

vendors:
  cobra:
    in: github.com/spf13/cobra
  term:
    in: golang.org/x/term
  yaml:
    in: gopkg.in/yaml.v3
  age:
    in:
      - filippo.io/age
      - filippo.io/age/**
  flock:
    in: github.com/gofrs/flock

components:
  cli:
    in: cli
  app:
    in: app
  manager:
    in: manager
  project:
    in: project
  secret:
    in: secret
  vault:
    in: vault
  jsonvault:
    in: jsonvault
  shelfage:
    in: age
  importer_gopass:
    in: importer/gopass
  config:
    in: config
  util:
    in: util

deps:
  cli:
    mayDependOn:
      - app
    canUse:
      - cobra
      - term


  app:
    mayDependOn:
      - config
      - manager
      - project
      - secret
      - vault
      - jsonvault
      - importer_gopass
      - util

  manager:
    mayDependOn:
      - util

  project:
    mayDependOn:
      - vault
      - util

  secret:
    mayDependOn:
      - vault

  jsonvault:
    mayDependOn:
      - vault
      - shelfage
      - util
    canUse:
      - flock

  shelfage:
    canUse:
      - age

  config:
    mayDependOn: []
    canUse:
      - yaml
