version: 3
workdir: internal

allow:
  depOnAnyVendor: false
  deepScan: true

excludeFiles:
  - "^.*_test\\.go$"

vendors:
  cobra:
    in: github.com/spf13/cobra
  term:
    in: golang.org/x/term
  yaml:
    in: gopkg.in/yaml.v3
  age:
    in:
      - filippo.io/age
      - filippo.io/age/**
  flock:
    in: github.com/gofrs/flock

components:
  cli:
    in: cli
  app:
    in: app
  manager:
    in: manager
  project:
    in: project
  secret:
    in: secret
  source:
    in: source
  shelfvault:
    in: adapters/shelfvault
  cryptoage:
    in: crypto/age
  config:
    in: config
  util:
    in: util

deps:
  cli:
    mayDependOn:
      - app
      - project
      - manager
    canUse:
      - cobra
      - term

  manager:
    mayDependOn:
      - app

  app:
    mayDependOn:
      - config
      - project
      - secret
      - source
      - shelfvault
      - cryptoage
      - util

  project:
    mayDependOn:
      - source
      - util

  secret:
    mayDependOn:
      - shelfvault

  source:
    mayDependOn:
      - util

  shelfvault:
    mayDependOn:
      - source
      - cryptoage
      - util
    canUse:
      - flock

  cryptoage:
    canUse:
      - age

  config:
    mayDependOn: []
    canUse:
      - yaml
