version: 2

project_name: shelf

builds:
  - id: shelf
    main: ./cmd/shelf
    binary: shelf
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -s -w -X github.com/zhongyangchuwu/shelf-go/internal/version.releaseVersion={{ .Version }}

archives:
  - id: shelf
    ids:
      - shelf
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{- .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}32-bit
      {{- else if eq .Arch "arm" }}armv6
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  use: github-native
  sort: asc

release:
  github:
    owner: zhongyangchuwu
    name: shelf-go
